theme: jekyll-theme-minimal
title: Pablo Riutort
description: <a href="https://github.com/pabloriutort/pabloriutort.github.io/raw/CV/cv.pdf">CV</a><br><a href="mailto:pablo.riutort@gmail.com">Email me</a><br><a href="https://stackoverflow.com/story/pabloriutort">Developer Story</a><br><a href="https://twitter.com/pabloriutort">@pabloriutort</a><br><a href="https://www.linkedin.com/in/pabloritutort/">LinkedIn</a><br><a href="https://medium.com/@pabloriutort">Blog</a>
